### PR TITLE
fix browser detection for iPhone

### PR DESCRIPTION
**Pull request by AgentCosmic**

### CODE REVIEW

**Comment by hthetiot** [comment]
lgtm

**Comment by hthetiot** [comment]
You may need to push on branch beta for your fixe to be merge by the maintainer.
(just saying that by experience.)

**Comment by EricDavies** [comment]
Two things:
  1) we need to get patch submitters to sign a form saying that our lives
aren't going to get complicated by lawyers if we accept your patch. I've
our CEO so he can send you the document that needs to be signed.
  2) the patch needs to be applied to the proper file. The easyrtc.js file
is the concatenation of several other files in the same directory; the
concatentation is done via the script "buildEnglishVersion.sh" . The one
that should be patched is probably adapter.js.

**Comment by hthetiot** [comment]
Should be good we take care of this userAgent issue now when we update adapter.js.

**Pull request closed without merging**
